services:
  - type: web
    name: bale-gemini-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: BALE_TOKEN
        value: your_bale_bot_token_here
      - key: GEMINI_API_KEY
        value: your_gemini_api_key_here
